apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagramreverseproxy
  name: udagramreverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagramreverseproxy  
  template:
    metadata:
      labels:
        service: udagramreverseproxy
    spec:
      containers:
      - image: pinmaing/udagram-reverse-proxy
        name: udagram-reverse-proxy
        imagePullPolicy: Always     
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always